### ISSUE TITLE
an error occurred when I wanted to read a 'std_msgs/String' type of data

### ISSUE THREAD

**Issue by Gribouillages** [jmscslgroup/bagpy#13]
code : 
       data = b.message_by_topic('/status/objects')
error:
      Traceback (most recent call last):
        File "/home/xxx/PycharmProjects/pythonProject/readRosbag.py", line 9, in <module>
          data = b.message_by_topic('/perception/objects')
        File "/home/xxx/.local/lib/python3.7/site-packages/bagpy/bagreader.py", line 266, in message_by_topic
          for topic, msg, t in self.reader.read_messages(topics=topic, start_time=tstart, end_time=tend): 
        File "/home/xxx/.local/lib/python3.7/site-packages/rosbag/bag.py", line 2699, in read_messages
          yield self.seek_and_read_message_data_record((entry.chunk_pos, entry.offset), raw, return_connection_header)
        File "/home/xxx/.local/lib/python3.7/site-packages/rosbag/bag.py", line 2874, in seek_and_read_message_data_record
          msg.deserialize(data)
        File "/tmp/genpy_0ui5frqm/tmpl21yqz9x.py", line 74, in deserialize
          self.data = str[start:end].decode('utf-8')
      UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 1: invalid continuation byte

**Comment by rahulbhadani** [comment]
Please check on https://stackoverflow.com/help/how-to-ask how to ask a better question and raise issues with potential reproducibility in mind. 

Besides, `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 1: invalid continuation byte` tells that your bagfile was not saved properly may be corrupted. You may try using native rosbag readers from `ROS` package via `import rosbag` and the result won't be different. You can cross-check my argument with rosbag reader from MATLAB at https://www.mathworks.com/help/ros/ref/rosbag.html
