### ISSUE TITLE
When I run bagpy code in the termianl after running 'python3' it works perfectly. however when I run the code in pycharm and then press run. I get this error. 

### ISSUE THREAD

**Issue by SharyatSB** [jmscslgroup/bagpy#17]
Traceback (most recent call last):
  File "/home/sharyat/training_data/trial.py", line 1, in <module>
    import bagpy
  File "/home/sharyat/.local/lib/python3.8/site-packages/bagpy/__init__.py", line 6, in <module>
    from .bagreader import bagreader
  File "/home/sharyat/.local/lib/python3.8/site-packages/bagpy/bagreader.py", line 42, in <module>
    from geometry_msgs.msg  import Twist, Pose, PoseStamped
ModuleNotFoundError: No module named 'geometry_msgs'

**Comment by rahulbhadani** [comment]
I do not use PyCharm and I do not how the python environment is configured in PyCharm. But if it works with python in the terminal, then the installation is correct. For generic questions related to PyCharm, please refer to Stackoverflow.

**Comment by rahulbhadani** [comment]
bagpy only decodes .bag files to .csv . There is no other features of bagpy at the moment.
