### ISSUE TITLE
Module object is bot callable

### ISSUE THREAD

**Issue by markusmat97** [jmscslgroup/bagpy#26]
I was reading a bag file 

import bagpy
from bagpy import bagreader

b = bagreader('C:\\Users\\xxxxxx\\PycharmProjects\\pythonProject1\\Data\\bagfile.bag')

and got this error...

Traceback (most recent call last):
  File "C:\Users\xxxxx\PycharmProjects\pythonProject1\rosbag.py", line 1, in <module>
    import bagpy
  File "C:\Users\xxxxx\PycharmProjects\pythonProject1\venv\lib\site-packages\bagpy\__init__.py", line 6, in <module>
    from .bagreader import bagreader
  File "C:\Users\xxxx\PycharmProjects\pythonProject1\venv\lib\site-packages\bagpy\bagreader.py", line 43, in <module>
    import rosbag
  File "C:\Users\xxxx\PycharmProjects\pythonProject1\rosbag.py", line 7, in <module>
    b = bagreader('C:\\Users\\xxxx\\PycharmProjects\\pythonProject1\\Data\\bagfile.bag')
TypeError: 'module' object is not callable

@rahulbhadani

**Comment by mathews997** [comment]
i tried like this  **from bagpy.bagreader import bagreader**  but it showed the error 
''ImportError: cannot import name 'bagreader' from partially initialized module 'bagpy.bagreader' (most likely due to a circular import)''
