### ISSUE TITLE
`pip search` command in `bagreader.py` should be removed

### ISSUE THREAD

**Issue by jsbyysheng** [jmscslgroup/bagpy#3]
Currently, `pip search` command in `bagreader.py` will cause the below error:
```
ERROR: Exception:
Traceback (most recent call last):
  File "/home/robotmws/anaconda3/envs/robot_py3/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/home/robotmws/anaconda3/envs/robot_py3/lib/python3.7/site-packages/pip/_internal/commands/search.py", line 62, in run
    pypi_hits = self.search(query, options)
  File "/home/robotmws/anaconda3/envs/robot_py3/lib/python3.7/site-packages/pip/_internal/commands/search.py", line 82, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/home/robotmws/anaconda3/envs/robot_py3/lib/python3.7/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/home/robotmws/anaconda3/envs/robot_py3/lib/python3.7/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/home/robotmws/anaconda3/envs/robot_py3/lib/python3.7/site-packages/pip/_internal/network/xmlrpc.py", line 46, in request
    return self.parse_response(response.raw)
  File "/home/robotmws/anaconda3/envs/robot_py3/lib/python3.7/xmlrpc/client.py", line 1342, in parse_response
    return u.close()
  File "/home/robotmws/anaconda3/envs/robot_py3/lib/python3.7/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -32500: "RuntimeError: PyPI's XMLRPC API has been temporarily disabled due to unmanageable load and will be deprecated in the near future. See https://status.python.org/ for more information.">
```
According to [pypa/pip issues 5216](https://github.com/pypa/pip/issues/5216), 
> The pip search command queries PyPI's servers, and PyPI's maintainers have explained that the API endpoint that the pip search command queries is very resource intensive and too expensive for them to always keep open to the public. Consequently they sometimes throttle access and are actually planning to remove it completely soon.

It'd better to use `pip install pip-search` according to this [post](https://stackoverflow.com/questions/65307988/error-using-pip-search-pip-search-stopped-working).

**Comment by rahulbhadani** [comment]
Thanks, I am was not aware of the `pip search` deprecation and removal plan.
I fixed the issue in https://pypi.org/project/bagpy/0.4.4/
